backend:
  name: github
  repo: rhmen201/Muslem-Parfum
  branch: main

# التعديل هنا: سيتم حفظ الصور داخل مجلد admin مباشرة لتجنب فقدانها
media_folder: "admin" 
public_folder: "admin"

collections:
  - name: "parfums"
    label: "العطور"
    folder: "admin/products" # سيقوم النظام بإنشاء هذا المجلد تلقائياً عند إضافة أول عطر
    create: true
    fields:
      - {label: "اسم العطر", name: "title", widget: "string"}
      - {label: "السعر", name: "price", widget: "number"}
      - {label: "الصورة", name: "image", widget: "image"}
      - {label: "الوصف", name: "body", widget: "markdown"}
