backend:
  name: git-gateway
  branch: main

media_folder: "admin"
public_folder: "admin"

collections:
  - name: "parfums"
    label: "العطور"
    folder: "admin/products"
    create: true
   fields:
      - {label: "اسم العطر", name: "title", widget: "string"}
      - {label: "السعر", name: "price", widget: "number"}
      - {label: "التصنيف", name: "category", widget: "select", options: ["رجالي", "نسائي", "للجنسين"]}
      - {label: "الصورة", name: "image", widget: "image"}
      - {label: "الوصف", name: "body", widget: "markdown"}

