backend:
  name: github
  repo: rhmen201/Muslem-Parfum
  branch: main

media_folder: "admin/images"
public_folder: "/admin/images"

collections:
  - name: "parfums"
    label: "العطور"
    folder: "admin/products"
    create: true
    fields:
      - {label: "اسم العطر", name: "title", widget: "string"}
      - {label: "السعر", name: "price", widget: "number"}
      - {label: "التصنيف", name: "category", widget: "select", options: ["رجالي", "نسائي", "عطور معتقة", "للجنسين"]}
      - {label: "الصورة", name: "image", widget: "image"}
      - {label: "وصف العطر", name: "body", widget: "markdown"}
      
